INSERT INTO FUNCIONARIO (NOME, RENDIMENTO_DIARIO) VALUES ('Usuario E', 18.0);
INSERT INTO FUNCIONARIO (NOME, RENDIMENTO_DIARIO) VALUES ('Usuario D', 22.0);
INSERT INTO FUNCIONARIO (NOME, RENDIMENTO_DIARIO) VALUES ('Usuario C', 32.0);
INSERT INTO FUNCIONARIO (NOME, RENDIMENTO_DIARIO) VALUES ('Usuario B', 37.0);
INSERT INTO FUNCIONARIO (NOME, RENDIMENTO_DIARIO) VALUES ('Usuario A', 80.0);